version: '1.0'

services:

  ticket-backend:
    image:  apajon/ticket-ideal-backend:latest
    environment:
      AWS_REGION: "us-east-1"
      AWS_SECRET_ACCESS_KEY: "UnhPWCcuKZ3d+AyqUoFMvpDeCTKyE+HDBhVJrPK7"
      AWS_ACCESS_KEY_ID: "ASIAZROVKZRN3OWBAEHT"
      AWS_SESSION_TOKEN: "FwoGZXIvYXdzEBQaDMa+LEIvBahgYg/nzSLMAa7/UOgMB4Rj2na4hcqkH4icnhRhiXWUzgP66WrZFjJY2XkuSwMhovryXHOExq2+C9AsFEtC2uwMtwXZn4YDIOHQBCNIooWDQure6ijzCTsZpXU2PLgYE0qJaBpuJWZdg0pjxZ7kg1hAFK7eH6h0koaA57Mnbe3wmnDRi0Y4SGJnIY8ZIXA42XPcu6YVd5rno7GJ6lPiJAn/SP6WZgOB7DpQ1i5vx6sMvCp2PxXOlqsjGqLWKMss/oimsML1X5un24ShGgoT16JwvJIrRij/ndmpBjItHNqHstxT+ByJRtaJ3d1sZmj12NwoY/gqfObaPjuq7aLTnyCbFZzijwJMlBWH"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    restart: always
    networks:
      - ticket-ideal

  ticket-frontend:
    image: apajon/ticket-ideal-frontend:latest
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - ticket-backend
    networks:
      - ticket-ideal

networks:
  ticket-ideal:

